"""empty message

Revision ID: 2d47747bd759
Revises: 
Create Date: 2023-10-18 14:52:38.915208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d47747bd759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'genres', ['genre_id'], ['genre_id'])

    with op.batch_alter_table('borrowing_goods', schema=None) as batch_op:
        batch_op.alter_column('nomor_induk',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing_goods', schema=None) as batch_op:
        batch_op.alter_column('nomor_induk',
               existing_type=sa.String(length=9),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('genre_id')

    op.drop_table('genres')
    # ### end Alembic commands ###
