"""empty message

Revision ID: c56a95c4f714
Revises: 
Create Date: 2023-10-19 22:47:09.473515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c56a95c4f714'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('goods')
    op.drop_table('borrowing_rooms')
    op.drop_table('borrowing_goods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowing_goods',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('good_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('borrowing_date', sa.DATE(), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.Column('nomor_induk', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['goods.id'], name='borrowing_goods_ibfk_1'),
    sa.ForeignKeyConstraint(['nomor_induk'], ['users.nomor_induk'], name='borrowing_goods_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('borrowing_rooms',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('room_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('borrowing_date', sa.DATE(), nullable=False),
    sa.Column('time_started', mysql.TIME(), nullable=False),
    sa.Column('time_ended', mysql.TIME(), nullable=True),
    sa.Column('nomor_induk', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['nomor_induk'], ['users.nomor_induk'], name='borrowing_rooms_ibfk_2'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='borrowing_rooms_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('goods',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rooms',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('capacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
